# Parameters for local CCDB file
# Format: (Type Module PathToFileForTimestamps)

qc_async tracks /ITS/MO/Tracks/NClustersPerTrackEta
qc_async clusters /ITS/MO/Clusters/Layer0/ClusterOccupation 
qc tracks /ITS/MO/ITSTrackTask/NClustersPerTrackEta
qc clusters /ITS/MO/ITSClusterTask/Layer0/ClusterOccupation
qc_mc tracks /ITS/MO/Tracks/NClustersPerTrackEta
qc_mc clusters /ITS/MO/Clusters/Layer0/ClusterOccupation
qc_mc simulation /ITS/MO/TracksMc/efficiency_phi
